### PR TITLE
MES-2323: TARS Upload Skeleton

### PR DESCRIPTION
**Pull request by ghost**
# Description and relevant Jira numbers
* Define the basic structure of TARS upload
* Call facades to fetch a batch and submit/report on it
* Split results into categories for completed/non-completed
* Still needs real implementation for fetching batches and uploading them.

## Pull Request checklist

- [x] [WIP] tag removed from PR title
- [x] PR has an understandable description

## Git feature branch checklist

- [x] branch name comply with our branching strategy
- [x] git branch contains relevant JIRA ticket number
- [x] branch rebased against the latest develop

## Sign off process checklist

- [ ] Code has been tested manually
- [ ] Tested by QA
- [ ] PO's approval
- [x] Reviewers selected in Github
- [x] PR link added to JIRA

### CODE REVIEW

**Review by rossfauldsbjss — APPROVED** [review]
Really nice bit of work.

**Review by szabikr — APPROVED** [review]
Looks like a very well thought out software design.

Is there a diagram which describes the relationships between the different components?

**Comment by ghost** [comment]
Not just yet @szabolcs-keresztes, just trying to get the division between domain and framework down as per the guideline of using hexagonal architecture. I will look into putting together a diagram once things start becoming a little more concrete.

**Comment by szabikr** [comment]
Okay, that's fine @johnmorleybjss . If you have the time and put together something eventually I would be happy to study it.

**Pull request merged**
